In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np



In [2]:
df = pd.read_csv('avocado_ripeness_dataset.csv')

In [4]:
color_dummies = pd.get_dummies(df['color_category'], prefix="color_category", dtype= int)
df = df.join(color_dummies)

In [5]:
ripenessDict = {
    'hard' : 1,
    'pre-conditioned' : 2,
    'breaking' : 3,
    'firm-ripe' : 4,
    'ripe' : 5,
}

df['target'] = df['ripeness'].apply(lambda x: ripenessDict[x])

In [6]:
x_cols = ['firmness', 'hue', 'saturation', 'brightness',
       'sound_db', 'weight_g', 'size_cm3', 'color_category_black',
       'color_category_dark green', 'color_category_green',
       'color_category_purple']
y_cols = ['target']

In [7]:
def shuffle_and_split_data(data, test_ratio):
    shuffled_indices = np.random.permutation(len(data))
    test_set_size = int(len(data) * test_ratio)
    test_indices = shuffled_indices[:test_set_size]
    train_indices = shuffled_indices[test_set_size:]
    return data.iloc[train_indices], data.iloc[test_indices]


df_train, df_test = shuffle_and_split_data(df, 0.2)
x_train = df_train[x_cols]
y_train = df_train[y_cols]
x_test = df_test[x_cols]
y_test = df_test[y_cols]

In [9]:
y_train_5 = (y_train == 5)
y_test_5 = (y_test == 5)

In [11]:
from sklearn.linear_model import SGDClassifier, LogisticRegression

sgd_clf = SGDClassifier(random_state=42)
sgd_clf.fit(x_train, y_train_5)

C:\Users\m.rahimi\PycharmProjects\browser-use\.venv\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SGDClassifier(random_state=42)

In [17]:
sgd_clf.predict([x_train.iloc[10]])

C:\Users\m.rahimi\PycharmProjects\browser-use\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(


array([False])

In [18]:
from sklearn.model_selection import cross_val_score
cross_val_score(sgd_clf,x_train, y_train_5, cv=5, scoring='accuracy')

C:\Users\m.rahimi\PycharmProjects\browser-use\.venv\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\m.rahimi\PycharmProjects\browser-use\.venv\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\m.rahimi\PycharmProjects\browser-use\.venv\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\m.rahimi\PycharmProjects\browser-use\.venv\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWar

array([1.   , 1.   , 0.975, 0.85 , 0.95 ])

In [19]:
from sklearn.dummy import DummyClassifier

dummy_clf = DummyClassifier()
dummy_clf.fit(x_train, y_train_5)

DummyClassifier()

In [20]:
cross_val_score(dummy_clf,x_train, y_train_5, cv=5, scoring='accuracy')

array([0.8  , 0.8  , 0.8  , 0.775, 0.775])

its a skewed dataset for now !

In [49]:
from sklearn.model_selection import cross_val_predict
y_train_5_pred = cross_val_predict(sgd_clf, x_train, y_train_5.to_numpy().ravel(), cv=3)

In [54]:
from sklearn.metrics import confusion_matrix,precision_score

confusion_matrix(y_train_5, y_train_5_pred)

array([[153,   5],
       [  0,  42]])

In [55]:
precision_score(y_train_5, y_train_5_pred)

0.8936170212765957